[package]
name = "ggpo-rs"
version = "0.1.0"
authors = ["assemblaj <assemblaj@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
